[versions]
agp = "9.3.2"
activity = "1.8.0"
lifecycle = "2.6.1"
playServicesAuth = "21.3.0"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }